### ISSUE TITLE
Project Requirements

### ISSUE THREAD

**Issue by yamesjamess** [yamesjamess/feb-24-hackathon-love-riot#13]
- [x] create wireframe
- [x] create database (if needed)
- [x] choose font family
- [x] create logo
- [x] pick colour scheme
- [x] gather assets (image ,icons, etc)
- [x] write content

**Comment by yamesjamess** [comment]
Colour scheme

![Image](https://github.com/yamesjamess/feb-24-hackathon-love-riot/assets/79316002/4bcdf3e2-d6c7-4c75-931d-51620d3225db)

**Comment by tarahwaters** [comment]
[Love_Riot_Stickers.zip](https://github.com/yamesjamess/feb-24-hackathon-love-riot/files/14301983/Love_Riot_Stickers.zip)

Attribution code for using these images - `<a href="https://www.flaticon.com/free-stickers/heart" title="heart stickers">Heart stickers created by alien.studio - Flaticon</a>`

Technology reference -[FlatIcon](https://www.flaticon.com/stickers)
Image Credit -[alien.studio](https://www.flaticon.com/authors/alienstudio)

![Image](https://github.com/yamesjamess/feb-24-hackathon-love-riot/assets/120593510/c58523fe-c1cb-45f0-ac7b-746ac58d2c46)

**Comment by tarahwaters** [comment]
Here is a functioning zodiac sign compatibility calculator based on % scores which we could base our logic on: [numerologysign.com](https://numerologysign.com/zodiac-signs-compatibility/)
There's a lot of useful information for astrological signs on this website (as well as this useful image detailing the birth dates for each sign):
[image source from numerology.com](https://numerologysign.com/zodiac-signs-explained-dates-meanings/)

![Image](https://github.com/yamesjamess/feb-24-hackathon-love-riot/assets/120593510/675c3faf-2df5-4e12-8103-f1b1eb9145e5)

**Comment by yamesjamess** [comment]
@tarahwaters I think that is the same with what @MelissaBuckingham  sends in the group chat last night

![image](https://github.com/yamesjamess/feb-24-hackathon-love-riot/assets/79316002/e80a6902-a463-49c3-a709-5513a06068b1)

**Comment by yamesjamess** [comment]
Font: https://fonts.google.com/specimen/Dosis
