### ISSUE TITLE
Research JavaScript Logic

### ISSUE THREAD

**Issue by tarahwaters** [yamesjamess/feb-24-hackathon-love-riot#31]
Discussion Friday evening (Slack huddle)

**Comment by tarahwaters** [comment]
This is potentially what we could try with the JS:
```
function calculateCompatibility(compatibilityData) {
  const sign1 = document.getElementById("sign1").value;
  const sign2 = document.getElementById("sign2").value;
  const compatibilityKey1 = `${sign1}-${sign2}`;
  const compatibilityKey2 = `${sign2}-${sign1}`;
  const compatibilityScore1 = compatibilityData[compatibilityKey1];
  const compatibilityScore2 = compatibilityData[compatibilityKey2];
  let compatibilityScore;
  if (compatibilityScore1 !== undefined && compatibilityScore2 !== undefined) {
    // Take the average of both compatibility scores
    compatibilityScore = (compatibilityScore1 + compatibilityScore2) / 2;
  } else if (compatibilityScore1 !== undefined) {
    compatibilityScore = compatibilityScore1;
  } else if (compatibilityScore2 !== undefined) {
    compatibilityScore = compatibilityScore2;
  }
  if (compatibilityScore !== undefined) {
    const compatibilityPercentage = compatibilityScore + "%";
    document.getElementById("result").textContent = `Compatibility between ${sign1} and ${sign2}: ${compatibilityPercentage}`;
  } else {
    document.getElementById("result").textContent = `Compatibility data not available for ${sign1} and ${sign2}`;
  }
}
```
Calling the function from the HTML button:
`<button type="button" onclick="calculateCompatibility(compatibilityData)">Calculate</button>`

The function first checks for the compatibility score for the selected signs in both orders (e.g., "Aries-Taurus" and "Taurus-Aries"). If both scores are available, it takes their average. If only one score is available, it uses that score. If no score is available for either combination, it displays a message indicating that the compatibility data is not available. This ensures that the calculation works regardless of the order in which the signs are selected.

Code help from chatGPT but will need to adapt and test it out for our page :)

**Comment by rstan-dev** [comment]
I think if the data holds all the combinations no matter which way you put the star sign it will generate the correct number - there is no need to do any kind of average.  The data set is incomplete for each start sign - Each sign needs a list of 12 marches and their corresponding number

**Comment by rstan-dev** [comment]
const compatibilityData = {
"Aries-Aries": 50, 
"Aries-Taurus": 38, 
"Aries-Gemini": 83, 
"Aries-Cancer": 42, 
"Aries-Leo": 97, 
"Aries-Virgo": 63, 
"Aries-Libra": 85, 
"Aries-Scorpio": 50, 
Aries-Sagittarius": 93, 
"Aries-Capricorn": 47, 
"Aries-Aquarius": 78, 
"Aries-Pisces": 67,
 
"Taurus-Aries": 38, 
"Taurus-Taurus": 65, 
"Taurus-Gemini": 33, 
"Taurus-Cancer": 97, 
Taurus-Leo": 73, "
Taurus-Virgo": 90, 
"Taurus-Libra": 65, 
"Taurus-Scorpio": 88, 
"Taurus-Sagittarius": 30, 
"Taurus-Capricorn": 98, 
Taurus-Aquarius": 58, 
"Taurus-Pisces": 85,

"Gemini-Aries": 83, 
"Gemini-Taurus": 33, 
"Gemini-Gemini": 60, 
"Gemini-Cancer": 65, 
Gemini-Leo": 88, 
"Gemini-Virgo": 68, 
"Gemini-Libra": 93, 
"Gemini-Scorpio": 28, 
"Gemini-Sagittarius": 60, 
"Gemini-Capricorn": 68, 
"Gemini-Aquarius": 85, 
"Gemini-Pisces": 53,

"Cancer-Aries": 42, 
"Cancer-Taurus": 97, 
"Cancer-Gemini": 65, 
"Cancer-Cancer": 75, 
"Cancer-Leo": 35, 
"Cancer-Virgo": 90, 
"Cancer-Libra": 43, 
"Cancer-Scorpio": 94, 
"Cancer-Sagittarius": 53, 
"Cancer-Capricorn": 83, 
"Cancer-Aquarius": 27, 
"Cancer-Pisces": 98,
    
"Leo-Aries": 97, 
"Leo-Taurus": 73, 
"Leo-Gemini": 88, 
Leo-Cancer": 35, 
"Leo-Leo": 45, 
"Leo-Virgo": 35, 
"Leo-Libra": 97, 
"Leo-Scorpio": 58, 
"Leo-Sagittarius": 93, 
"Leo-Capricorn": 35, 
"Leo-Aquarius": 68, 
"Leo-Pisces": 38,
    
"Virgo-Aries": 63, 
"Virgo-Taurus": 90, 
"Virgo-Gemini": 68, 
Virgo-Cancer": 90, 
"Virgo-Leo": 35, 
"Virgo-Virgo": 65, 
"Virgo-Libra": 68, 
Virgo-Scorpio": 88, 
"Virgo-Sagittarius": 48, 
"Virgo-Capricorn": 95, 
"Virgo-Aquarius": 30, 
"Virgo-Pisces": 88,
    
"Libra-Aries": 85, 
"Libra-Taurus": 65, 
"Libra-Gemini": 93, 
"Libra-Cancer": 43, 
"Libra-Leo": 97, 
"Libra-Virgo": 68,
"Libra-Libra": 75, 
"Libra-Scorpio": 35, 
"Libra-Sagittarius": 73,
"Libra-Capricorn": 55, 
"Libra-Aquarius": 90, 
"Libra-Pisces": 88,
    
"Scorpio-Aries": 50,
"Scorpio-Taurus": 88,
"Scorpio-Gemini": 28, 
"Scorpio-Cancer": 94, 
"Scorpio-Leo": 58, 
"Scorpio-Virgo": 88, 
"Scorpio-Libra": 35, 
"Scorpio-Scorpio": 80, 
"Scorpio-Sagittarius": 28, 
"Scorpio-Capricorn": 95, 
"Scorpio-Aquarius": 73, 
"Scorpio-Pisces": 97,
"Sagittarius-Aries": 93, 
"Sagittarius-Taurus": 30, 
"Sagittarius-Gemini": 60, 
"Sagittarius-Cancer": 53, 
"Sagittarius-Leo": 93, 
"Sagittarius-Virgo": 48, 
"Sagittarius-Libra": 73, 
"Sagittarius-Scorpio": 28, 
"Sagittarius-Sagittarius": 45, 
"Sagittarius-Capricorn": 60, 
"Sagittarius-Aquarius": 90, 
"Sagittarius-Pisces": 63,
    
"Capricorn-Aries": 47, 
"Capricorn-Taurus": 98, 
"Capricorn-Gemini": 68, 
Capricorn-Cancer": 83, 
"Capricorn-Leo": 35, 
"Capricorn-Virgo": 95, 
"Capricorn-Libra": 55, 
"Capricorn-Scorpio": 95, 
"Capricorn-Sagittarius": 60, 
"Capricorn-Capricorn": 75, 
"Capricorn-Aquarius": 68, 
"Capricorn-Pisces": 88,
    
"Aquarius-Aries": 78, 
"Aquarius-Taurus": 58, 
"Aquarius-Gemini": 85, 
"Aquarius-Cancer": 27, 
"Aquarius-Leo": 68, 
"Aquarius-Virgo": 30, 
"Aquarius-Libra": 90, 
"Aquarius-Scorpio": 73, 
"Aquarius-Sagittarius": 90, 
"Aquarius-Capricorn": 68, 
"Aquarius-Aquarius": 45, 
"Aquarius-Pisces": 45,
    
"Pisces-Aries": 67, 
"Pisces-Taurus": 85, 
"Pisces-Gemini": 53, 
"Pisces-Cancer": 98, 
"Pisces-Leo": 38, 
"Pisces-Virgo": 88, 
"Pisces-Libra": 88, 
"Pisces-Scorpio": 97, 
"Pisces-Sagittarius": 63, 
"Pisces-Capricorn": 88, 
"Pisces-Aquarius": 45, 
"Pisces-Pisces": 60
};

**Comment by tarahwaters** [comment]
> I think if the data holds all the combinations no matter which way you put the star sign it will generate the correct number - there is no need to do any kind of average. The data set is incomplete for each start sign - Each sign needs a list of 12 marches and their corresponding number

Ohh sure! I thought it saved us from writing out all combinations but seems you have it sorted anyway 😀 🙏
