### ISSUE TITLE
Initial Project Ideas

### ISSUE THREAD

**Issue by tarahwaters** [yamesjamess/feb-24-hackathon-love-riot#32]
As a developer I want to be able to come up with ideas for my project, so that I can start developing.

**Comment by yamesjamess** [comment]
Compatibility Calculator by @MeganRoberts-dev

**Comment by yamesjamess** [comment]
Love Match Game (kinda like memory match but guess who should match with who) by @yamesjamess

**Comment by yamesjamess** [comment]
Team went with Compatibility calculator with astronomy/zodiac sign compatibility
