### ISSUE TITLE
HTML / CSS for compatibility results page

### ISSUE THREAD

**Issue by tarahwaters** [yamesjamess/feb-24-hackathon-love-riot#33]
This is the page we discussed about showing the user how we get the results that we are showing them

**Comment by yamesjamess** [comment]
https://html-shark.com/HTML/Zodiac.htm zodiac symbols

**Comment by yamesjamess** [comment]
anoter website used for content https://www.zodiacsign.com/compatibility/virgo/

**Comment by yamesjamess** [comment]
half way done

**Comment by yamesjamess** [comment]
page is completed
