### ISSUE TITLE
About page for the team

### ISSUE THREAD

**Issue by yamesjamess** [yamesjamess/feb-24-hackathon-love-riot#34]
Github profile
James - https://github.com/yamesjamess
Russ - https://github.com/rstan-dev
Megan - https://github.com/MeganRoberts-dev
Tarah - https://github.com/tarahwaters
Melissa - https://github.com/MelissaBuckingham
Ilyas - https://github.com/ilyasolgun11

Linkedin
James - https://www.linkedin.com/in/james-kasetarapanya-86602585/
Russ - https://www.linkedin.com/in/russellstanleysmith/
Megan - https://www.linkedin.com/in/megan-roberts-5874b1205/
Tarah - https://www.linkedin.com/in/tarah-w-563256b5/
Melissa - https://www.linkedin.com/in/melissa-buckingham/
Ilyas - https://www.linkedin.com/in/ilyascan-olgun-455290182/

Having images would be nice. If you want to provide image that would be great, or will pull image from Github API

**Comment by MeganRoberts-dev** [comment]
About section - 
Ah, splendid! Allow us to introduce ourselves: we are Cupid and Co, we're a lively bunch of love enthusiasts, dedicated to spreading the joy of sustainable, everlasting love. With a steadfast determination to spare hearts from the sting of disappointment, we've concocted the marvellous "Love Riot" website. It's a great place where eager souls can suss out the compatibility of names and star signs before taking the plunge into the whirlwind of a date. No need to rush into things here friend! Just a spot of good-natured matchmaking to ensure that amour blossoms with the finest of prospects. So, why rush into matters of the heart when you can indulge in a bit of pre-date prognostication? Join us at Love Riot, where love's potential is assessed with British precision and a dash of whimsy! Cheers to love everlasting!

**Comment by rstan-dev** [comment]
here is the code we used for the about page for the last Hackathaon - no API, just pics needed from Linked in


<body>

    <div class="container main-container my-auto">
      <div class="row text-center">
          <div class="col-12 py-4">
              <h1> Meet the BUDG€T€€R$! </h1>
          </div>


          <div class=" col-md-6 col-sm-12" id="anny">
              <a href="https://www.linkedin.com/in/anny-devoy-09a58950/">
                  <img src="/static/media/about-us-anny.png" alt="Anny's Image" class="img-fluid rounded-circle avatar">
              </a>
              <p class="about-card-text customize-button w-100">Anny
                <a href="https://www.linkedin.com/in/anny-devoy-09a58950/">
                    <i class="fab fa-linkedin"></i>
                </a>
          </div>

          <div class=" col-md-6 col-sm-12" id="bekry">
              <a href="https://www.linkedin.com/in/bekry-mohammed/">
                  <img src="/static/media/about-us-bekry.jpg" alt="Bekry's Image" class="img-fluid rounded-circle avatar">
              </a>
              <p class="about-card-text customize-button w-100">Bekry
                <a href="https://www.linkedin.com/in/bekry-mohammed/">
                    <i class="fab fa-linkedin"></i>
                </a>
              </p>
          </div>

          <div class=" col-md-6 col-sm-12" id="jakub">
              <a href="https://www.linkedin.com/in/jakub-bulejcik-334474106/">
                  <img src="/static/media/about-us-jakub.jpg" class="img-fluid rounded-circle avatar">
              </a>
              <p class="about-card-text customize-button w-100">Jakub
                <a href="https://www.linkedin.com/in/jakub-bulejcik-334474106/">
                    <i class="fab fa-linkedin"></i>
                </a>
              </p>
          </div>

            <div class=" col-md-6 col-sm-12" id="richard">
                <a href="https://www.linkedin.com/in/richardmarles-webdeveloper/">
                    <img src="/static/media/about-us-richard.png" class="img-fluid rounded-circle avatar">
                </a>
                <p class="about-card-text customize-button w-100">Richard
                    <a href="https://www.linkedin.com/in/richardmarles-webdeveloper/">
                        <i class="fab fa-linkedin"></i>
                    </a>
                </p>
            </div>

            <div class=" col-md-6 col-sm-12" id="russ">
                <a href="https://www.linkedin.com/in/russellstanleysmith/">
                    <img src="/static/media/about-us-russ.jpg" class="img-fluid rounded-circle avatar">
                </a>
                <p class="about-card-text customize-button w-100">Russ
                <a href="https://www.linkedin.com/in/russellstanleysmith/">
                    <i class="fab fa-linkedin"></i>
                </a>
                </p>
            </div>

            <div class=" col-md-6 col-sm-12" id="sam">
                <a href="https://www.linkedin.com/in/sam-o-brien-olinger-b658283a/">
                    <img src="/static/media/Sam.jpg" class="img-fluid rounded-circle avatar">
                </a>
                <p class="about-card-text customize-button w-100">Sam
                <a href="https://www.linkedin.com/in/sam-o-brien-olinger-b658283a/">
                    <i class="fab fa-linkedin"></i>
                </a>
                </p>
            </div>

      </div>
  </div>
