### ISSUE TITLE
Email sending issue with enter button

### ISSUE THREAD

**Issue by rstan-dev** [yamesjamess/feb-24-hackathon-love-riot#58]

**Comment by rstan-dev** [comment]
when I press enter on my keyboard after filling out the email, the page refreshes and the email is not sent out. If I click send then it sends out an email

**Comment by yamesjamess** [comment]
reventDefault() needs to be add somewhere, not sure where

**Comment by yamesjamess** [comment]
I've fix this issue by adding this code the email.js

`document.getElementById('email').addEventListener('keydown', function(event) {
    if (event.key === 'Enter') {
        event.preventDefault();
        document.getElementById('sendEmail').click();
    }
});
`
